orbs:
  docker: circleci/docker@1.5.0
version: 2.1
executors:
  docker-publisher: 
    environment:
      IMAGE_NAME: sundarsudandiraraj/random-tvshow-node-app
    docker:
      - image: circleci/node:latest
        auth:
            username: $DOCKERHUB_USERNAME
            password: $DOCKERHUB_PASSWORD

jobs:
    publishLatestToHub: 
      executor: docker-publisher
 
      steps: 
        - checkout
        - setup_remote_docker
        - run: 
            name: Publish Docker Image to Docker Hub
            command: |
              TAG=1.0.$CIRCLE_BUILD_NUM
              echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
              docker build -t $IMAGE_NAME:$TAG .
              docker push $IMAGE_NAME:$TAG
    
    GenerateDeploymentYAML:
      docker:
        - image: cimg/base:2020.06
      steps:
        - run : |
            TAG=1.0.$CIRCLE_PREVIOUS_BUILD_NUM
            git clone https://github.com/sundarsudandiraraj/random-tvshow-cd.git /tmp/CircleCI-Webapp-CD
            cd /tmp/CircleCI-Webapp-CD/.k8s
            sed -i 's/\(random-tvshow-node-app\)\(.*\)/\1:'$TAG'/' ./deployment.yaml
            git config credential.helper 'cache --timeout=120'
            git config user.email "CircleCI@sundar.co"
            git config user.name "CircleCI"
            git add .
            git commit -m "Update via CircleCI"
            # Push quietly to prevent showing the token in log
            git push origin master



workflows:
  version: 2
  build-master:
    jobs:
       - publishLatestToHub
       - GenerateDeploymentYAML:
          requires:
            - publishLatestToHub
          
                
                 
             
    
       
      


    
           
   
    

    